// <auto-generated />
using System;
using Mamey.Government.Modules.CitizenshipApplications.Core.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mamey.Government.Modules.CitizenshipApplications.Core.EF.Migrations
{
    [DbContext(typeof(CitizenshipApplicationsDbContext))]
    partial class CitizenshipApplicationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("citizenship_applications")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mamey.Government.Modules.CitizenshipApplications.Core.Domain.Entities.ApplicationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_application_tokens");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_application_tokens_application_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_application_tokens_email");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_application_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_application_tokens_token_hash");

                    b.HasIndex("UsedAt")
                        .HasDatabaseName("ix_application_tokens_used_at")
                        .HasFilter("\"used_at\" IS NOT NULL");

                    b.HasIndex("TokenHash", "Email")
                        .HasDatabaseName("ix_application_tokens_token_hash_email");

                    b.ToTable("application_tokens", "citizenship_applications");
                });

            modelBuilder.Entity("Mamey.Government.Modules.CitizenshipApplications.Core.Domain.Entities.CitizenshipApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessLogsJson")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("access_logs_json");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_number");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("approved_by");

                    b.Property<string>("ContactInformation")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("contact_information");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CriminalHistory")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("criminal_history");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Dependents")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("dependents");

                    b.Property<string>("EducationQualifications")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("education_qualifications");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmploymentHistory")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("employment_history");

                    b.Property<string>("ExtendedDataJson")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("extended_data_json");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fee");

                    b.Property<string>("ForeignCitizenshipApplications")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("foreign_citizenship_applications");

                    b.Property<string>("ForeignIdentification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("foreign_identification");

                    b.Property<bool?>("HaveCriminalRecord")
                        .HasColumnType("boolean")
                        .HasColumnName("have_criminal_record");

                    b.Property<bool?>("HaveForeignCitizenshipApplication")
                        .HasColumnType("boolean")
                        .HasColumnName("have_foreign_citizenship_application");

                    b.Property<decimal>("IdentificationCardFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("identification_card_fee");

                    b.Property<string>("ImmigrationHistories")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("immigration_histories");

                    b.Property<bool>("IsPrimaryApplication")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary_application");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<string>("PersonalDetails")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("personal_details");

                    b.Property<string>("References")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("references");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rejected_by");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("ResidencyHistory")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("residency_history");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<bool>("RushToCitizen")
                        .HasColumnType("boolean")
                        .HasColumnName("rush_to_citizen");

                    b.Property<bool>("RushToDiplomacy")
                        .HasColumnType("boolean")
                        .HasColumnName("rush_to_diplomacy");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Step")
                        .HasColumnType("integer")
                        .HasColumnName("step");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_application_number");

                    b.HasIndex("ApprovedAt")
                        .HasDatabaseName("ix_applications_approved_at")
                        .HasFilter("\"approved_at\" IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_applications_created_at");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_applications_email")
                        .HasFilter("\"email\" IS NOT NULL");

                    b.HasIndex("PaymentTransactionId")
                        .HasDatabaseName("ix_applications_payment_transaction_id")
                        .HasFilter("\"payment_transaction_id\" IS NOT NULL");

                    b.HasIndex("RejectedAt")
                        .HasDatabaseName("ix_applications_rejected_at")
                        .HasFilter("\"rejected_at\" IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_applications_status");

                    b.HasIndex("Step")
                        .HasDatabaseName("ix_applications_step");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_applications_submitted_at")
                        .HasFilter("\"submitted_at\" IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_applications_tenant_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_applications_updated_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_applications_status_created_at");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_applications_tenant_id_created_at");

                    b.HasIndex("TenantId", "PaymentTransactionId")
                        .HasDatabaseName("ix_applications_tenant_id_payment_transaction_id")
                        .HasFilter("\"payment_transaction_id\" IS NOT NULL");

                    b.HasIndex("TenantId", "ReviewedBy")
                        .HasDatabaseName("ix_applications_tenant_id_reviewed_by")
                        .HasFilter("\"reviewed_by\" IS NOT NULL");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_applications_tenant_id_status");

                    b.HasIndex("TenantId", "Step")
                        .HasDatabaseName("ix_applications_tenant_id_step");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_applications_tenant_id_status_created_at");

                    b.HasIndex("TenantId", "Status", "Step")
                        .HasDatabaseName("ix_applications_tenant_id_status_step");

                    b.ToTable("applications", "citizenship_applications");
                });

            modelBuilder.Entity("Mamey.Government.Modules.CitizenshipApplications.Core.Domain.Entities.UploadedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_uploaded_documents");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_uploaded_documents_application_id");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("ix_uploaded_documents_document_type");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_uploaded_documents_uploaded_at");

                    b.HasIndex("ApplicationId", "DocumentType")
                        .HasDatabaseName("ix_uploaded_documents_application_id_document_type");

                    b.ToTable("uploaded_documents", "citizenship_applications");
                });

            modelBuilder.Entity("Mamey.MicroMonolith.Infrastructure.Messaging.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_inbox");

                    b.ToTable("inbox", "citizenship_applications");
                });

            modelBuilder.Entity("Mamey.MicroMonolith.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.ToTable("outbox", "citizenship_applications");
                });

            modelBuilder.Entity("Mamey.Government.Modules.CitizenshipApplications.Core.Domain.Entities.CitizenshipApplication", b =>
                {
                    b.OwnsOne("Mamey.Types.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("FirmName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_firm_name");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("address_is_default");

                            b1.Property<string>("Line")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("Line3")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line3");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Province")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_province");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_type");

                            b1.Property<string>("Urbanization")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_urbanization");

                            b1.Property<string>("Zip4")
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("address_zip4");

                            b1.Property<string>("Zip5")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("address_zip5");

                            b1.HasKey("id")
                                .HasName("pk_applications");

                            b1.ToTable("applications", "citizenship_applications");

                            b1.WithOwner()
                                .HasForeignKey("id")
                                .HasConstraintName("fk_applications_applications_id");
                        });

                    b.OwnsOne("Mamey.Types.Name", "ApplicantName", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name_last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name_middle_name");

                            b1.Property<string>("Nickname")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name_nickname");

                            b1.HasKey("id")
                                .HasName("pk_applications");

                            b1.ToTable("applications", "citizenship_applications");

                            b1.WithOwner()
                                .HasForeignKey("id")
                                .HasConstraintName("fk_applications_applications_id");
                        });

                    b.OwnsOne("Mamey.Types.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_country_code");

                            b1.Property<string>("Extension")
                                .HasColumnType("text")
                                .HasColumnName("phone_extension");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("phone_is_default");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("phone_type");

                            b1.HasKey("id")
                                .HasName("pk_applications");

                            b1.ToTable("applications", "citizenship_applications");

                            b1.WithOwner()
                                .HasForeignKey("id")
                                .HasConstraintName("fk_applications_applications_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("ApplicantName")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Mamey.Government.Modules.CitizenshipApplications.Core.Domain.Entities.UploadedDocument", b =>
                {
                    b.HasOne("Mamey.Government.Modules.CitizenshipApplications.Core.Domain.Entities.CitizenshipApplication", "Application")
                        .WithMany("Uploads")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uploaded_documents_applications_application_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Mamey.Government.Modules.CitizenshipApplications.Core.Domain.Entities.CitizenshipApplication", b =>
                {
                    b.Navigation("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
