name: Accessibility Issue
description: Report an accessibility barrier or suggest an improvement
title: "[A11Y] "
labels: ["accessibility", "good-first-issue"]
body:
  - type: markdown
    attributes:
      value: |
        ## ♿ Accessibility Issue Report
        Thank you for helping us make the Ierahkwa Platform accessible to everyone.
        The Ierahkwa Platform follows the GAAD Pledge and targets WCAG 2.2 AA compliance.

  - type: dropdown
    id: platform
    attributes:
      label: Which platform or service is affected?
      options:
        - Portal Soberano
        - Cloud Soberana
        - Correo Soberano
        - Docs Soberanos
        - Code Soberano
        - Canal Soberano
        - Música Soberana
        - Media Soberana
        - Navegador Soberano
        - Conferencia Soberana
        - Empresa Soberana
        - Vigilancia Soberana
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    id: barrier-type
    attributes:
      label: Type of accessibility barrier
      options:
        - Visual (color contrast, text size, screen reader)
        - Motor (keyboard navigation, touch targets)
        - Auditory (captions, audio alternatives)
        - Cognitive (navigation, language, error messages)
        - Assistive Technology compatibility
        - Other
    validations:
      required: true

  - type: dropdown
    id: assistive-tech
    attributes:
      label: Assistive technology used (if applicable)
      options:
        - NVDA
        - JAWS
        - VoiceOver (macOS/iOS)
        - TalkBack (Android)
        - Dragon NaturallySpeaking
        - Switch Access
        - ZoomText
        - Eye Tracking
        - Keyboard only
        - None / Not applicable
        - Other

  - type: textarea
    id: description
    attributes:
      label: Description of the barrier
      description: What were you trying to do and what happened?
      placeholder: |
        I was trying to navigate the platform using keyboard only...
        Expected: Tab should move focus to the navigation menu
        Actual: Focus is trapped in the hero section
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does this barrier affect your ability to use the platform?
      placeholder: I cannot access the main content without using a mouse.

  - type: dropdown
    id: wcag
    attributes:
      label: Related WCAG criterion (if known)
      options:
        - "1.1.1 Non-text Content"
        - "1.3.1 Info and Relationships"
        - "1.4.1 Use of Color"
        - "1.4.3 Contrast (Minimum)"
        - "1.4.11 Non-text Contrast"
        - "2.1.1 Keyboard"
        - "2.4.1 Bypass Blocks"
        - "2.4.3 Focus Order"
        - "2.4.7 Focus Visible"
        - "4.1.2 Name, Role, Value"
        - "Not sure"

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have checked that this issue has not already been reported
          required: true
