// <auto-generated />
using System;
using Mamey.ApplicationName.Modules.Products.Core.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mamey.ApplicationName.Modules.Products.Core.EF.Migrations
{
    [DbContext(typeof(BankingProductDbContext))]
    [Migration("20241231024858_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("banking-products-module")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InterestRateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LimitsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TermsAndConditions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LimitsId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.ApplicableTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankingProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BankingProductId");

                    b.ToTable("ApplicableTaxes", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankingProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("BenefitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BankingProductId");

                    b.ToTable("Benefits", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.EligibilityCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankingProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Geography")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinimumIncome")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OtherCriteria")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BankingProductId")
                        .IsUnique();

                    b.ToTable("EligibilityCriterias", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.Fee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("BankingProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BankingProductId");

                    b.ToTable("Fees", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.InterestRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankingProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompoundingFrequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankingProductId")
                        .IsUnique();

                    b.ToTable("InterestRates", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.Limits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankingProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DailyTransactionLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MaximumBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinimumBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WithdrawalLimit")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Limits", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.RequiredDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankingProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BankingProductId");

                    b.ToTable("RequiredDocuments", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.MicroMonolith.Infrastructure.Messaging.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Inbox", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.MicroMonolith.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "banking-products-module");
                });

            modelBuilder.Entity("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", b =>
                {
                    b.HasOne("Mamey.ApplicationName.Modules.Products.Core.Entities.Limits", "Limits")
                        .WithOne("Product")
                        .HasForeignKey("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", "LimitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Limits");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.ApplicableTax", b =>
                {
                    b.HasOne("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", "Product")
                        .WithMany("ApplicableTaxes")
                        .HasForeignKey("BankingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.Benefit", b =>
                {
                    b.HasOne("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", "Product")
                        .WithMany("Benefits")
                        .HasForeignKey("BankingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.EligibilityCriteria", b =>
                {
                    b.HasOne("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", "Product")
                        .WithOne("EligibilityCriteria")
                        .HasForeignKey("Mamey.ApplicationName.Modules.Products.Core.Entities.EligibilityCriteria", "BankingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.Fee", b =>
                {
                    b.HasOne("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", "Product")
                        .WithMany("Fees")
                        .HasForeignKey("BankingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.InterestRate", b =>
                {
                    b.HasOne("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", "Product")
                        .WithOne("InterestRate")
                        .HasForeignKey("Mamey.ApplicationName.Modules.Products.Core.Entities.InterestRate", "BankingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.RequiredDocument", b =>
                {
                    b.HasOne("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", "Product")
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("BankingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mamey.Bank.Modules.BankingProducts.Core.Entities.Product", b =>
                {
                    b.Navigation("ApplicableTaxes");

                    b.Navigation("Benefits");

                    b.Navigation("EligibilityCriteria")
                        .IsRequired();

                    b.Navigation("Fees");

                    b.Navigation("InterestRate");

                    b.Navigation("RequiredDocuments");
                });

            modelBuilder.Entity("Mamey.ApplicationName.Modules.Products.Core.Entities.Limits", b =>
                {
                    b.Navigation("Product")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
