// <auto-generated />
using System;
using Pupitre.Progress.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Pupitre.Progress.Infrastructure.EF.Migrations
{
    [DbContext(typeof(LearningProgressDbContext))]
    partial class LearningProgressDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mamey.MessageBrokers.Outbox.Messages.InboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_inbox");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("Mamey.MessageBrokers.Outbox.Messages.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MessageContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_context");

                    b.Property<string>("MessageContextType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_context_type");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<string>("OriginatedMessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("originated_message_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SerializedMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serialized_message");

                    b.Property<string>("SerializedMessageContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serialized_message_context");

                    b.Property<string>("SpanContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("span_context");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Pupitre.Progress.Domain.Entities.LearningProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockchainAccount")
                        .HasColumnType("text")
                        .HasColumnName("blockchain_account");

                    b.Property<string>("BlockchainMetadata")
                        .HasColumnType("text")
                        .HasColumnName("blockchain_metadata");

                    b.Property<string>("CitizenId")
                        .HasColumnType("text")
                        .HasColumnName("citizen_id");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialDocumentHash")
                        .HasColumnType("text")
                        .HasColumnName("credential_document_hash");

                    b.Property<string>("CredentialDocumentId")
                        .HasColumnType("text")
                        .HasColumnName("credential_document_id");

                    b.Property<DateTime?>("CredentialIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("credential_issued_at");

                    b.Property<string>("CredentialStatus")
                        .HasColumnType("text")
                        .HasColumnName("credential_status");

                    b.Property<string>("CredentialType")
                        .HasColumnType("text")
                        .HasColumnName("credential_type");

                    b.Property<string>("GovernmentIdentityId")
                        .HasColumnType("text")
                        .HasColumnName("government_identity_id");

                    b.Property<string>("LedgerTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<string>("ProgramCode")
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_learningprogress");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_learningprogress_name");

                    b.ToTable("learningprogress", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
